# Corpo do Documento Acadêmico

Em seu documento principal (*master*), o início do documento acadêmico propriamente dito é marcado pelo 
seguinte comando:

    %% Início do documento
    \begin{document}

Já o fim do documento acadêmico é marcado por:

    %% Fim do documento
    \end{document}
    
Assim sendo, tudo aquilo que constitui o documento acadêmico, sejam eles elementos pré-textuais, textuais, e 
pós-textuais, são inserido entre os comandos `\begin{document}` e `\end{document}`.

### Elementos pré-textuais obrigatórios

Você precisa informar `UFRuralRJ` onde os elementos pré-textuais devem ser inseridos. Para isso, basta usar os
seguintes comandos (nesta ordem):

    %% Inserir capa, folha de rosto, e folha de aprovação
    \maketitle
    \makeapprove

Pronto!!! Desde que todas as informações necessárias tenham sido passadas à `UFRuralRJ` acima, no preâmbulo do 
seu documento principal, os dois simples comandos `\maketitle` e `\makeapprove` se encarregarão do serviço de
formatar e posicionar no local correto a capa, a folha de rosto, e a folha de aprovação do seu documento 
acadêmico, sem que você tenha que fazer qualquer esforço. Mas lembre-se de que eles devem ser inseridos sempre
após `\begin{document}`.

### Elementos pré-textuais opcionais



### Mais elementos pré-textuais obrigatórios

#### Resumo do documento acadêmico

Um importante elemento pré-textual obrigatório é o resumo do documento acadêmico. A classe `UFRuralRJ` possui
dois tipos de resumo, cada um pensado para um tipo de documento acadêmico. O primeiro deles é o que chamamos de
*resumo geral*. O resumo geral é usado em documentos acadêmicos construídos usando capítulos individuais, ou
seja, capítulos preparados de maneira que possam ser lidos individualmente, muitas vezes baseados em 
trabalhos publicados em revistas científicas na forma de artigo, revisão bibliográfica, ou nota científica. 
O outro tipo de resumo do documento acadêmico oferecido por `UFRuralRJ` é o que chamamos de *resumo simples*, 
o qual corresponde ao resumo de todo o documento acadêmico quando o mesmo é construído a partir de capítulos 
sequenciais, ou seja, como \emph{texto corrido}.

Consideremos o exemplo acima, onde nosso documento acadêmico constitui uma tese de doutorado composta por 
capítulos individuais. Nesse caso, usa-se o *resumo geral*, primeiro em português:

    %% Definições do resumo geral
    \def\tituloPT{UFRuralRJ -- Classe \LaTeX{} para formatação de documentos acadêmicos na UFRRJ}
    \def\chavesPT{\LaTeX. UFRuralRJ. Documentos acadêmicos}
    \def\nivelPT{Doutorado em Agronomia, Ciência do Solo}
    
    %% Resumo geral
    \generalabstracttrue
    \begin{generalabstract}{brazilian}{\tituloPT}{\chavesPT}{\nivelPT}
    Este é o resumo geral em português de uma tese organizada na forma de capítulos individuais.
    \end{generalabstract}

Depois em inglês:

    %% General abstract definitions
    \def\tituloEN{UFRuralRJ -- \LaTeX{} class for formatting academic documents at UFRRJ}
    \def\chavesEN{\LaTeX. UFRuralRJ. Academical documents}
    \def\nivelEN{Doctor of Science in Agronomy, Soil Science}
    
    %% General abstract
    \generalabstracttrue
    \begin{generalabstract}{english}{\tituloEN}{\chavesEN}{\nivelEN}
    This is the English abstract of a thesis organized in the form of individual chapters.
    \end{generalabstract}

Primeiro, vejamos qual a diferença entre o *resumo geral* e o *resumo simples*. Note, nos exemplos acima, a
macro `\generalabstracttrue`. É esta macro a responsável por informar à `UFRuralRJ` que o resumo que estamos
construindo é do tipo geral ao invés de simples. Assim, no caso de *resumo simples*, basta remover a macro
`\generalabstracttrue`, ou usar `\generalabstractfalse`. Simples assim!!!

Vejamos agora os outros elementos usados para definir o resumo de nosso documento acadêmico. Para ambos o 
*resumo geral* e o *resumo simples*, o resumo do documento acadêmico sempre é construído usando o ambiente
`generalabstract`, o qual aceita cinco informações: o idioma do resumo, o título do documento acadêmico, as 
palavras-chave, o nível do grau obtido, e o texto do resumo.

    \begin{generalabstract}{<idioma>}{<titulo>}{<palavras-chaves>}{<nivel>}
    <texto>
    \end{generalabstract}

Com exceção do texto do resumo, todas as outras informações são passadas entre chaves, conforme demonstrado
acima. A soma dessas informações geralmente resulta em um linha bastante longa. A fim de facilitar a
manipulação e leitura de nosso documento, podemos usar as funcionalidades do LaTeX e criar definições para
cada um dos itens do resumo usando o comando [`\def`][def]. Aqui, o comando `\def` recebe dois argumentos: o 
primeiro é a identificação daquilo que estamos definindo; o segundo é o seu conteúdo. Assim, o comando

    \def\chavesPT{\LaTeX. UFRuralRJ. Documentos acadêmicos}

resulta na definição de um novo comando chamado `\chavesPT`, o qual contém as palavras-chave em português, tal 
qual definido em `{\LaTeX. UFRuralRJ. Documentos acadêmicos}`. A função do novo comando `\chavesPT` é inserir,
no local onde for usado, as palavras-chave em português. (Note que o uso de `\def` é puramente estética.)

#### Listas e sumário

Os últimos elementos pré-textuais obrigatórios são as listas e os sumários. Atualmente, `UFRuralRJ` suporta o
uso de quatro tipos de listas: figuras, tabelas, apêndices, e anexos. Para inserir essas listas no documento 
basta usar os seguintes comandos:

    \listoffigures  %% Lista de figuras
    \listoftables   %% Lista de tabelas
    \listofappendix %% Lista de apêndices
    \listofannex    %% Lista de anexos

Para inserir o [sumário][toc], basta usar o seguinte comando:

    \tableofcontents

Novamente, tudo muito simples, graças à capacidade de `UFRuralRJ` identificar, automaticamente, quais itens ao
longo do texto pertencem a cada lista ou ao sumário. Caso seu documento não possua figuras, tabelas, apêndices,
ou anexos, basta remover o respectivo comando mostrado acima.

### Corpo principal do documento acadêmico

O corpo principal do documento acadêmico é constituído pelo texto propriamente dito, isto é, aquilo que você 
escreveu a cerca de suas experiências científicas ao longo dos anos de seu curso. A forma de organização desse 
texto pode variar conforme descrito acima. Também existem diferentes maneira de você gerenciar esse texto. Uma 
delas é redigindo todo o texto no seu documento `*.tex` principal. Contudo, do ponto de vista organizacional, 
essa não é uma boa estratégia pois o seu documento `*.tex` principal ficará extremamente longo, dificultando a 
navegação ao longo do mesmo. Além disso, um documento muito longo acaba usando grande quantidade da memória do 
seu computador.

A melhor estratégia de gerenciar o texto de seu documento acadêmico é usar um arquivo individual para cada 
parte ou capítulo. Especificamente, você usa um arquivo `*.tex` individual para escrever a Introdução Geral,
outro arquivo `*.tex` para o Capítulo I, outro arquivo `*.tex` para as Conclusões Gerais, e assim por diante.
Apesar do exemplo para documentos acadêmicos organizados na forma de capítulos individuais, o mesmo se aplica
para documentos em texto corrido. Por exemplo, imagine que você escreveu tese com cinco grandes partes 
principais: Introdução, Revisão da Literatura, Material e Métodos, Resultados, Discussão, e Conclusões. Basta
escrever cada uma dessas grandes partes principais em um arquivo `*.tex` individual.

Os arquivos `*.tex` individuais usados para redigir cada capítulo ou cada grande parte principal do documento
acadêmico devem ser armazenados em um diretório também individual a fim de garantir melhor organização do 
trabalho. Feito isso, basta usar o comando [`\include`][include], conforme segue:

    %% Incluir texto do corpo principal
    \include{capitulos/introducao.tex}
    \include{capitulos/capitulo01.tex}
    \include{capitulos/capitulo02.tex}
    \include{capitulos/conclusao.tex}

No nosso exemplo, todos os arquivos `*.tex` individuais estão armazenados em um diretório chamado `capitulos`.
Os nomes dos arquivos permitem adivinhar o seu conteúdo. Aqui, o comando `\include` cumprirá a tarefa de 
incluir, exatamente neste ponto do documento, o conteúdo da Introdução Geral, dos dois capítulos, e da 
Conclusão Geral. Se, por acaso, mais tarde, você e seus orientadores decidirem modificar a ordem dos capítulos
no documento acadêmico, basta alterar a ordem em que cada arquivo `*.tex` é incluído. Simples assim!

O último item do corpo principal do documento acadêmico é a lista de referências bibliográficas. Para inserir 
essa lista no seu documento acadêmico basta usar simples o comando [`\bibliography`][bibliography]:

    %% Inserir lista de referências bibliográficas
    \bibliography{referencias/biblio.bib}

onde `referencias` é o nome do diretório onde se encontra sua base de dados de referências bibliográficas no 
formato [BibTeX][bibtex], e `biblio.bib` é o nome dessa base de dados de referências bibliográficas.

